apiVersion: apps/v1
kind: Deployment
metadata:
  name: hkasdd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hkasdd
  template:
    metadata:
      labels:
        app: hkasdd
    spec:
      containers:
      - image: okteto.dev/hkasdd:latest
        name: hkasdd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "5a6cf4ee-0642-11ed-b939-0242ac120002"
        - name: Vless_Path
          value: "/vl56B55"
        - name: Vmess_UUID
          value: "5a6cf4ee-0642-11ed-b939-0242ac120002"
        - name: Vmess_Path
          value: "/vm66K86"
        - name: Share_Path
          value: "/v2link"
